Importing pandas

In [1]:
import datetime
print(f"Last updated: {datetime.datetime.now()}")

Last updated: 2026-09-09 14:49:56.388287

importing pandas

In [2]:
import pandas as pd

# Print the version
print(f"pandas version: {pd.__version__}")

pandas version: 3.0.5

Datatypes

In [3]:
# Creating a series of car types
cars = pd.Series(["BMW", "Toyota", "Honda"])
cars

0       BMW
1    Toyota
2     Honda
dtype: str

In [4]:
# Creating a series of colours
colours = pd.Series(["Blue", "Red", "White"])
colours

0     Blue
1      Red
2    White
dtype: str

In [5]:
# Creating a DataFrame of cars and colours
car_data = pd.DataFrame({"Car type": cars, 
                         "Colour": colours})
car_data

  Car type Colour
0      BMW   Blue
1   Toyota    Red
2    Honda  White

Practice of bike data

In [6]:
bikes=pd.Series(["Yamaha", "Suzuki", "Kawasaki"])
bikes

0      Yamaha
1      Suzuki
2    Kawasaki
dtype: str

In [7]:
Price=pd.Series([1000, 2000, 3000])
Price

0    1000
1    2000
2    3000
dtype: int64

In [8]:
bike_data=pd.DataFrame({"Bike_types":bikes,
                        "Price":Price})
bike_data

  Bike_types  Price
0     Yamaha   1000
1     Suzuki   2000
2   Kawasaki   3000

In [9]:
# Example solution

# Make a Series of different foods
foods = pd.Series(["Almond butter", "Eggs", "Avocado"])

# Make a Series of different dollar values 
prices = pd.Series([9, 6, 2])

# Combine your Series of foods and dollar values into a DataFrame
food_data = pd.DataFrame({"Foods": foods,
                          "Price": prices})

food_data

           Foods  Price
0  Almond butter      9
1           Eggs      6
2        Avocado      2

 Importing data

In [15]:
# Import car sales data
car_sales = pd.read_csv("/Users/shahjalalmd/Desktop/pandas/pandas-sj-data-science/car_sales.csv") # takes a filename as string as input

car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [17]:
# Import the car sales data and save it to df

# Read from a CSV file (stored on our local computer)
df = pd.read_csv("/Users/shahjalalmd/Desktop/pandas/pandas-sj-data-science/car_sales.csv")


df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

Exporting data

In [18]:
# Export the car sales DataFrame to csv
car_sales.to_csv("/Users/shahjalalmd/Desktop/pandas/pandas-sj-data-science/exported_car_sales.csv")

Example solution

In [20]:
# Importing heart-disease.csv
patient_data = pd.read_csv("/Users/shahjalalmd/Desktop/pandas/pandas-sj-data-science/heart.csv")
patient_data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0